language: node_js
os: linux
node_js:
  - 'lts/*'

before_deploy:
  - npm run build:docker
  - npm run test

deploy:
  provider: script
  script: bash docker_push
  on:
    branches:
      only:
      - gh-pages
      - /.*/