version: "3.8"

services:
  db:
    image: postgis/postgis:12-3.0-alpine
    volumes:
      - uk-geoboundaries-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./src/.env.local
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  web:
    image: "covid-near-me:${VERSION:-1}"
    restart: always
    env_file: ./src/.env.local
    environment:
      POSTGRES_HOST: db
    build:
      context: .
      dockerfile: ./src/DOCKERFILE
    ports:
      - "3000:3000"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  uk-geoboundaries-data:
    external: true