version: "3.3"

services:
  db:
    image: "uk-geoboundaries:${VERSION:-1}"
    restart: always
    build:
      context: .
      dockerfile: ./db/DOCKERFILE
    env_file: ./src/.env.local
    ports:
      - "5432:5432"

  web:
    image: "covid-near-me:${VERSION:-1}"
    restart: always
    env_file: ./src/.env.local
    environment:
      POSTGRES_HOST: db
    build:
      context: .
      dockerfile: ./src/DOCKERFILE
    ports:
      - "3000:3000"
    depends_on:
      - db
