version: "3.3"

services:
  web:
    image: "covid-near-me:${VERSION:-1}"
    restart: always
    env_file: ./src/.env.local
    environment:
      POSTGRES_HOST: db
    build:
      context: .
      dockerfile: ./src/DOCKERFILE
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: "doniseferi/uk-geoboundaries:1.0.0"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_TIMEOUT_IN_SECONDS: 10
    ports:
      - "5432:5432"
