FROM node:12.18.4-alpine3.12

RUN mkdir -p /usr
WORKDIR /usr/app

COPY src /usr/app/src
COPY tsconfig.json /usr/app
COPY package.json /usr/app


RUN npm install
RUN npm run build
EXPOSE 3000
CMD npm run start